-- 总账核心表

-- 会计科目表
CREATE TABLE IF NOT EXISTS `gl_account` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `company_id` BIGINT NOT NULL COMMENT '公司ID',
    `account_code` VARCHAR(20) NOT NULL COMMENT '科目编码',
    `account_name` VARCHAR(100) NOT NULL COMMENT '科目名称',
    `parent_id` BIGINT DEFAULT NULL COMMENT '上级科目ID',
    `level` INT DEFAULT 1 COMMENT '层级',
    `account_type` VARCHAR(20) NOT NULL COMMENT '科目类型',
    `balance_direction` VARCHAR(10) NOT NULL COMMENT '余额方向',
    `auxiliary_dept` TINYINT DEFAULT 0 COMMENT '部门核算',
    `auxiliary_project` TINYINT DEFAULT 0 COMMENT '项目核算',
    `auxiliary_customer` TINYINT DEFAULT 0 COMMENT '客户核算',
    `auxiliary_supplier` TINYINT DEFAULT 0 COMMENT '供应商核算',
    `auxiliary_employee` TINYINT DEFAULT 0 COMMENT '员工核算',
    `status` TINYINT DEFAULT 0 COMMENT '状态',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_code` (`company_id`, `account_code`),
    KEY `idx_parent_id` (`parent_id`),
    KEY `idx_account_type` (`account_type`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会计科目表';

-- 凭证表
CREATE TABLE IF NOT EXISTS `gl_voucher` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `company_id` BIGINT NOT NULL COMMENT '公司ID',
    `voucher_no` VARCHAR(30) NOT NULL COMMENT '凭证号',
    `accounting_year` INT NOT NULL COMMENT '会计年度',
    `accounting_period` INT NOT NULL COMMENT '会计期间',
    `voucher_date` DATE NOT NULL COMMENT '凭证日期',
    `voucher_type` VARCHAR(20) DEFAULT NULL COMMENT '凭证类型',
    `abstract` VARCHAR(500) DEFAULT NULL COMMENT '摘要',
    `total_debit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '借方合计',
    `total_credit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '贷方合计',
    `entry_count` INT DEFAULT 0 COMMENT '分录数量',
    `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状态',
    `maker_id` BIGINT DEFAULT NULL COMMENT '制单人ID',
    `maker_name` VARCHAR(50) DEFAULT NULL COMMENT '制单人',
    `audit_time` DATETIME DEFAULT NULL COMMENT '审核时间',
    `auditor_id` BIGINT DEFAULT NULL COMMENT '审核人ID',
    `auditor_name` VARCHAR(50) DEFAULT NULL COMMENT '审核人',
    `post_time` DATETIME DEFAULT NULL COMMENT '过账时间',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_voucher_no` (`company_id`, `accounting_year`, `accounting_period`, `voucher_no`),
    KEY `idx_company_period` (`company_id`, `accounting_year`, `accounting_period`),
    KEY `idx_voucher_date` (`voucher_date`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证表';

-- 凭证分录表
CREATE TABLE IF NOT EXISTS `gl_voucher_entry` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `voucher_id` BIGINT NOT NULL COMMENT '凭证ID',
    `line_no` INT NOT NULL COMMENT '行号',
    `account_id` BIGINT NOT NULL COMMENT '科目ID',
    `account_code` VARCHAR(20) NOT NULL COMMENT '科目编码',
    `account_name` VARCHAR(100) NOT NULL COMMENT '科目名称',
    `abstract` VARCHAR(500) DEFAULT NULL COMMENT '摘要',
    `debit_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '借方金额',
    `credit_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '贷方金额',
    `currency` VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    `exchange_rate` DECIMAL(10,6) DEFAULT 1.000000 COMMENT '汇率',
    `dept_id` BIGINT DEFAULT NULL COMMENT '部门ID',
    `project_id` BIGINT DEFAULT NULL COMMENT '项目ID',
    `customer_id` BIGINT DEFAULT NULL COMMENT '客户ID',
    `supplier_id` BIGINT DEFAULT NULL COMMENT '供应商ID',
    `employee_id` BIGINT DEFAULT NULL COMMENT '员工ID',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_voucher_line` (`voucher_id`, `line_no`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_account_code` (`account_code`),
    KEY `idx_debit_amount` (`debit_amount`),
    KEY `idx_credit_amount` (`credit_amount`),
    KEY `idx_dept_id` (`dept_id`),
    KEY `idx_project_id` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证分录表';

-- 会计期间表
CREATE TABLE IF NOT EXISTS `gl_accounting_period` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `company_id` BIGINT NOT NULL COMMENT '公司ID',
    `accounting_year` INT NOT NULL COMMENT '会计年度',
    `accounting_period` INT NOT NULL COMMENT '期间',
    `start_date` DATE NOT NULL COMMENT '开始日期',
    `end_date` DATE NOT NULL COMMENT '结束日期',
    `status` VARCHAR(20) DEFAULT 'opened' COMMENT '状态',
    `close_time` DATETIME DEFAULT NULL COMMENT '结账时间',
    `closer_id` BIGINT DEFAULT NULL COMMENT '结账人ID',
    `closer_name` VARCHAR(50) DEFAULT NULL COMMENT '结账人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_year_period` (`company_id`, `accounting_year`, `accounting_period`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会计期间表';

-- 科目余额表
CREATE TABLE IF NOT EXISTS `gl_balance` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `company_id` BIGINT NOT NULL COMMENT '公司ID',
    `account_id` BIGINT NOT NULL COMMENT '科目ID',
    `account_code` VARCHAR(20) NOT NULL COMMENT '科目编码',
    `account_name` VARCHAR(100) NOT NULL COMMENT '科目名称',
    `accounting_year` INT NOT NULL COMMENT '会计年度',
    `accounting_period` INT NOT NULL COMMENT '期间',
    `beginning_debit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '期初借方',
    `beginning_credit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '期初贷方',
    `current_debit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '本期借方',
    `current_credit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '本期贷方',
    `ending_debit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '期末借方',
    `ending_credit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '期末贷方',
    `dept_id` BIGINT DEFAULT NULL COMMENT '部门ID',
    `project_id` BIGINT DEFAULT NULL COMMENT '项目ID',
    `customer_id` BIGINT DEFAULT NULL COMMENT '客户ID',
    `supplier_id` BIGINT DEFAULT NULL COMMENT '供应商ID',
    `employee_id` BIGINT DEFAULT NULL COMMENT '员工ID',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_account_period` (`company_id`, `account_id`, `accounting_year`, `accounting_period`, `dept_id`, `project_id`, `customer_id`, `supplier_id`, `employee_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_account_code` (`account_code`),
    KEY `idx_company_year_period` (`company_id`, `accounting_year`, `accounting_period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科目余额表';

-- 客户档案表
CREATE TABLE IF NOT EXISTS `ba_customer` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `company_id` BIGINT NOT NULL COMMENT '公司ID',
    `customer_code` VARCHAR(30) NOT NULL COMMENT '客户编码',
    `customer_name` VARCHAR(100) NOT NULL COMMENT '客户名称',
    `short_name` VARCHAR(50) DEFAULT NULL COMMENT '客户简称',
    `customer_type` VARCHAR(20) DEFAULT NULL COMMENT '客户类型',
    `contact_person` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    `phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    `address` VARCHAR(200) DEFAULT NULL COMMENT '地址',
    `tax_no` VARCHAR(50) DEFAULT NULL COMMENT '税号',
    `bank_name` VARCHAR(100) DEFAULT NULL COMMENT '开户行',
    `bank_account` VARCHAR(50) DEFAULT NULL COMMENT '银行账号',
    `credit_limit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '信用额度',
    `status` TINYINT DEFAULT 0 COMMENT '状态',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_code` (`company_id`, `customer_code`),
    KEY `idx_customer_name` (`customer_name`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户档案表';

-- 供应商档案表
CREATE TABLE IF NOT EXISTS `ba_supplier` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `company_id` BIGINT NOT NULL COMMENT '公司ID',
    `supplier_code` VARCHAR(30) NOT NULL COMMENT '供应商编码',
    `supplier_name` VARCHAR(100) NOT NULL COMMENT '供应商名称',
    `short_name` VARCHAR(50) DEFAULT NULL COMMENT '供应商简称',
    `supplier_type` VARCHAR(20) DEFAULT NULL COMMENT '供应商类型',
    `contact_person` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    `phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    `address` VARCHAR(200) DEFAULT NULL COMMENT '地址',
    `tax_no` VARCHAR(50) DEFAULT NULL COMMENT '税号',
    `bank_name` VARCHAR(100) DEFAULT NULL COMMENT '开户行',
    `bank_account` VARCHAR(50) DEFAULT NULL COMMENT '银行账号',
    `credit_limit` DECIMAL(18,2) DEFAULT 0.00 COMMENT '信用额度',
    `status` TINYINT DEFAULT 0 COMMENT '状态',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_code` (`company_id`, `supplier_code`),
    KEY `idx_supplier_name` (`supplier_name`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商档案表';

-- 项目档案表
CREATE TABLE IF NOT EXISTS `ba_project` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `company_id` BIGINT NOT NULL COMMENT '公司ID',
    `project_code` VARCHAR(30) NOT NULL COMMENT '项目编码',
    `project_name` VARCHAR(100) NOT NULL COMMENT '项目名称',
    `project_type` VARCHAR(20) DEFAULT NULL COMMENT '项目类型',
    `manager` VARCHAR(50) DEFAULT NULL COMMENT '负责人',
    `start_date` DATE DEFAULT NULL COMMENT '开始日期',
    `end_date` DATE DEFAULT NULL COMMENT '结束日期',
    `budget_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '预算金额',
    `description` TEXT DEFAULT NULL COMMENT '项目描述',
    `status` TINYINT DEFAULT 0 COMMENT '状态',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_code` (`company_id`, `project_code`),
    KEY `idx_project_name` (`project_name`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目档案表';
