spring:
  application:
    name: openaccounting-ledger

  datasource:
    url: jdbc:mysql://localhost:3306/openaccounting?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  level:
    com.qoobot.openaccounting.ledger: debug
